from .EntropySGD import EntropySGD
from .Ranger import Ranger
from .SVRG import SVRG
from .Lookahead import Lookahead
from .RAdam import *
from .Shampoo import *
from .SWA import *
from .Diffgrad import *
from .KFAC import *
from .Yogi import *
from .types import *